spring:
  application:
    name: rohlik-demo
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5434/rohlik
    username: rohlik
    password: rohlik
    driver-class-name: org.postgresql.Driver
